### ISSUE TITLE
Throw new error ('Not opened'); 

### ISSUE THREAD

**Issue by Avalanchewolf** [ProbablePrime/beam-keyboard#24]
Disconnected retrying after 1000
Reconnecting :D
Authenticated, Spinning up Interactive Connection
Process is exiting wih code: 1
C:\Users\david\Desktop\interactive-keyboard-master\node_modules\beam-interactive-node\node_modules\ws\lib\WebSocket.js:160
    throw new Error('not opened');
    ^

Error: not opened
    at WebSocket.ping (C:\Users\david\Desktop\interactive-keyboard-master\node_modules\beam-interactive-node\node_modules\ws\lib\WebSocket.js:160:11)
    at RobotHeartbeats._ping (C:\Users\david\Desktop\interactive-keyboard-master\node_modules\beam-interactive-node\dist\robot\heartbeats.js:35:26)
    at null._onTimeout (C:\Users\david\Desktop\interactive-keyboard-master\node_modules\beam-interactive-node\dist\heartbeats.js:86:31)
    at Timer.listOnTimeout (timers.js:92:15)

Any ideas after about 10-20mins it does this?

**Comment by ProbablePrime** [comment]
Bad internet causes that usually.

**Comment by Avalanchewolf** [comment]
MY internet in business class with 60Mbps down and 10Mbps upload, i dont see it being a issue from my internet. Could my windows firewall be blocking it sometimes?

**Comment by ProbablePrime** [comment]
This particular problem relates to internet quality and not speed. Something is closing your connection. We can handle that better and i'm working on that but this project isn't even released. Right now fixing it would be ensuring connection quality or writing a script to automatically restart your controls when they die.

**Comment by Avalanchewolf** [comment]
Okay ill look into a script to restart the controls when they die thank you so much!
