### ISSUE TITLE
Unhandled Rejection TypeError

### ISSUE THREAD

**Issue by Rackera** [ProbablePrime/beam-keyboard#33]
`Unhandled rejection TypeError: Cannot read property 'controls' of undefined
    at Client.<anonymous> (C:\Users\david\Desktop\interactive-keyboard\index.js:512:32)
    at Client.tryCatcher (C:\Users\david\Desktop\interactive-keyboard\node_modules\beam-client-node\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\david\Desktop\interactive-keyboard\node_modules\beam-client-node\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (C:\Users\david\Desktop\interactive-keyboard\node_modules\beam-client-node\node_modules\bluebird\js\main\promise.js:584:18)
    at Async._drainQueue (C:\Users\david\Desktop\interactive-keyboard\node_modules\beam-client-node\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\Users\david\Desktop\interactive-keyboard\node_modules\beam-client-node\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\david\Desktop\interactive-keyboard\node_modules\beam-client-node\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)` 

That is the error I am having

**Comment by Rackera** [comment]
Not having this error anymore, had the wrong version.
